spring:
  h2:
    console:
      enabled: true
      path: /h2-console #http://localhost:8080/h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:group-trivia;DB_CLOSE_DELAY=-1
    username: sa
    password:
    initialize: true
  jpa:
     hibernate:
      ddl-auto: create